# Configuration file for JuliaFormatter.jl
# Formatting options are described here: https://github.com/domluna/JuliaFormatter.jl

indent = 4
margin = 80
remove_extra_newlines = true
trailing_comma = false

always_for_in = true
always_use_return = true

whitespace_typedefs = true
whitespace_ops_in_indices = true
whitespace_in_kwargs = true

verbose = true
overwrite = true